---
openapi: 3.0.2
info:
  title: 商品
  version: 1.0.0
paths:
  /product:
    summary: 商品情報管理
    get:
      parameters:
      - name: id
        description: ""
        schema:
          type: string
        in: query
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: 正常終了
      summary: 商品情報を取得する
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        required: true
      responses:
        "200":
          description: 正常終了
        "500":
          content:
            application/json:
              schema:
                type: string
          description: 異常終了
      summary: 商品情報を作成する
    delete:
      responses:
        "200":
          description: 削除成功
      summary: 商品情報を削除する
  /price:
    summary: 価格情報
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/price'
        required: true
      responses:
        "200":
          description: 正常終了
      summary: 価格情報を更新する
components:
  schemas:
    product:
      description: ""
      required:
      - name
      - price
      - id
      type: object
      properties:
        name:
          description: 名称
          type: string
        sales_date:
          format: date-time
          description: 発売日
          type: string
        price:
          $ref: '#/components/schemas/price'
          description: 価格情報
        variation_products:
          description: バリエーション商品
          type: array
          items:
            $ref: '#/components/schemas/variation'
        id:
          description: ID
          type: string
      example:
        id: "0001"
        name: some text
        sales_date: 2018-02-10T09:30Z
        price:
          price: 18
          tax: 89.44
        variation_products:
        - product:
            name: some text
            sales_date: 2018-02-10T09:30Z
            price:
              price: 46
              tax: 57.24
            variation_products:
            - {}
            - {}
            id: some text
        - product:
            name: some text
            sales_date: 2018-02-10T09:30Z
            price:
              price: 65
              tax: 6.75
            variation_products:
            - {}
            - {}
            id: some text
    price:
      description: ""
      required:
      - price
      - tax
      - id
      type: object
      properties:
        price:
          description: 商品価格
          type: integer
        tax:
          format: double
          description: 税率
          type: number
        id:
          description: 'ID  '
          type: string
      example:
        id: "0001"
        price: 39
        tax: 54.17
    variation:
      description: バリエーション
      type: object
      properties:
        product:
          $ref: '#/components/schemas/product'
          description: 商品情報
      example:
        product:
          name: some text
          sales_date: 2018-02-10T09:30Z
          price:
            id: "0001"
            price: 35
            tax: 31.99
          variation_products:
          - product: {}
          - product: {}
          id: some text
